<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Professional Tax Statement — {{ $monthName }} {{ $year }} — {{ $company->company_name ?? 'Company' }}</title>
    @include('statutory._pdf_styles')
</head>
<body>

<div class="actions">
    <button onclick="window.print()">🖨 Save as PDF</button>
    <button class="secondary" onclick="window.close()">Close</button>
</div>

<div class="sheet">

    <div class="gov-header">
        <div class="top">
            <div>
                <h1>Professional Tax — Monthly Remittance Statement</h1>
                <h2>State Tax on Professions, Trades, Callings &amp; Employments</h2>
                <div style="font-size:10.5px;margin-top:2px">Statement of tax deducted at source from salary &amp; wages — to be paid to State Govt. (Profession Tax Acts of respective States)</div>
            </div>
            <div class="form-no">
                Form&nbsp;5&nbsp;/&nbsp;PTRC<br><small>(System-generated)</small>
            </div>
        </div>
        <hr>
        <div class="meta">
            <div>
                <div><strong>Employer Name:</strong> {{ $company->company_name ?? '—' }}</div>
                <div><strong>PT Registration (PTRC):</strong> {{ $company->pt_state_reg_no ?? '—' }}</div>
                <div><strong>Address:</strong>
                    {{ trim(($company->registered_address_line1 ?? '') . ', ' . ($company->registered_address_line2 ?? ''), ', ') ?: '—' }}
                </div>
                <div><strong>PAN / TAN:</strong> {{ $company->pan ?? '—' }} / {{ $company->tan ?? '—' }}</div>
            </div>
            <div>
                <div><strong>Wage Month:</strong> {{ $monthName }} {{ $year }}</div>
                <div><strong>Salary Group:</strong> {{ $group->salary_group_name ?? 'All Groups' }}</div>
                <div><strong>Total Employees:</strong> {{ $rows->count() }}</div>
                <div><strong>Generated On:</strong> {{ now()->format('d-M-Y H:i') }}</div>
            </div>
        </div>
    </div>

    <table class="gov-table">
        <thead>
            <tr>
                <th style="width:30px">Sr.</th>
                <th style="width:60px">Emp ID</th>
                <th style="width:240px">Employee Name</th>
                <th style="width:80px">State</th>
                <th style="width:200px">Slab Applied</th>
                <th style="width:90px">PT Amount<br>(₹)</th>
                <th style="width:80px">Status</th>
            </tr>
        </thead>
        <tbody>
            @forelse($rows as $i => $r)
                <tr>
                    <td class="c">{{ $i + 1 }}</td>
                    <td class="c">{{ $r->emp_id }}</td>
                    <td class="l">{{ $r->employee_name ?? '—' }}</td>
                    <td class="c">{{ $r->state ?? '—' }}</td>
                    <td class="l">{{ $r->slab_applied ?? '—' }}</td>
                    <td class="r">{{ number_format($r->pt_amount ?? 0, 0) }}</td>
                    <td class="c">{{ $r->status ?? 'Generated' }}</td>
                </tr>
            @empty
                <tr><td colspan="7" class="c" style="padding:24px">No PT records for this period. Click "Generate PT" first.</td></tr>
            @endforelse

            @if($rows->count())
                <tr class="totals-row">
                    <td class="label" colspan="5">TOTAL PT REMITTANCE</td>
                    <td class="r">₹ {{ number_format($total, 0) }}</td>
                    <td class="c">—</td>
                </tr>
            @endif
        </tbody>
    </table>

    <div class="declaration">
        <b>Declaration:</b> I/We hereby certify that the above particulars of professional tax deducted from the salary of
        employees for the month stated are true and correct. The amount will be remitted to the State Treasury within the
        prescribed due date under the applicable State Profession Tax Act.
    </div>

    <div class="sigs">
        <div class="blk">
            <div class="lbl">Signature of Employer / Authorised Signatory</div>
            <div>{{ $company->authorized_signatory_name ?? '________________________' }}</div>
            <div style="font-size:10px; color:#555">{{ $company->authorized_signatory_designation ?? '' }}</div>
        </div>
        <div class="blk">
            <div class="lbl">Place &amp; Date</div>
            <div>______________________ &nbsp; {{ now()->format('d-M-Y') }}</div>
        </div>
        <div class="blk">
            <div class="lbl">Employer Seal</div>
            <div style="height:36px"></div>
        </div>
    </div>

    <div class="footer">
        <div>PT Monthly Statement — System generated by Hreasy by WebSenor on {{ now()->format('d-M-Y H:i') }}</div>
        <div>Page 1 of 1</div>
    </div>
</div>

</body>
</html>
